name: compile

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build_and_test:
    name: Build Buffer overflows on ${{ matrix.os }} with ${{ matrix.compiler }}.
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        compiler: [ g++-10 ]
        include:
          - os: ubuntu-latest
            compiler: g++-10
            target: Linux

          - os: macos-latest
            compiler: g++-10
            target: Macos

          - os: windows-latest
            compiler: cl
            target: Windows

    steps:
      
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install gcc for 32 bits
        run: sudo apt install -y gcc-multilib g++-multilib
        
      - name: Compile a release build 
        run: cd stringformats && make
        
      - name: Zip
        run: cd stringformats && zip vuln.zip vuln
        
      - name: Upload linux artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./stringformats/vuln.zip
          asset_name: vuln.zip
          asset_content_type: application/gzip
